spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://root:Zi71Fs1_lMSSgeSEZuVd1y_YZf6Hr16cl_BUkVrZ4fjv9toQ@f4b91bc0-e38c-4e42-b42f-8b3698854594.asia-southeast1.firestore.goog:443/db-capstone?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0